# Generated by Django 4.0.6 on 2022-07-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usersab_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersab',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
