# Generated by Django 4.0.6 on 2022-08-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usersab_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersab',
            name='total_gold',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usersab',
            name='gold',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
