# Generated by Django 4.0.6 on 2023-05-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersab_is_ban_usersab_number_usersab_open_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersab',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Users/'),
        ),
    ]
