# Generated by Django 4.2.1 on 2023-06-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usersab_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersab',
            name='is_ban',
        ),
    ]
