# Generated by Django 4.2.1 on 2023-06-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_usersab_is_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersab',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
