# Generated by Django 4.0.4 on 2022-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StandId', models.CharField(default='', max_length=250)),
                ('nickname', models.CharField(default='', max_length=250)),
                ('image', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
