# Generated by Django 4.0.6 on 2022-07-20 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.FloatField(null=True)),
                ('gold_commision', models.FloatField(null=True)),
                ('data', models.DateTimeField(auto_now=True, null=True)),
                ('is_ordered', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='orders',
            name='skin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.skins'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
