# Generated by Django 4.0.6 on 2022-08-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orders_skins_delete_userinfo_orders_skin_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='skins',
            name='image',
            field=models.ImageField(default=None, upload_to='SKINS/%Y/%m/%d'),
        ),
    ]
