# Generated by Django 4.0.6 on 2022-08-01 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_skins_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='gold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='gold_commision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='is_ordered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='skin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.skins'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
