# Generated by Django 4.0.6 on 2022-08-01 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_orders_gold_alter_orders_gold_commision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='gold',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='gold_commision',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
