# Generated by Django 4.0.6 on 2023-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_casescategory_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='skin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
