# Generated by Django 4.0.6 on 2023-05-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_orders_skin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary'), ('Arcane', 'Arcane'), ('Knife', 'Knife'), ('Gloves', 'Gloves'), ('Gold', 'Gold')], default='Common', max_length=255)),
                ('image', models.ImageField(upload_to='ITEMS/')),
                ('sell_gold', models.FloatField(default=0)),
                ('chance', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cases',
            name='items',
            field=models.ManyToManyField(to='main.items'),
        ),
    ]
